micronaut:
  application:
    name: micronautEmptyJavaMaven
camunda:
  admin-user:
    id: admin
    password: admin
  webapps:
    enabled: true
  rest:
    enabled: true
  generic-properties:
    properties:
      initialize-telemetry: true
  filter:
    create: All tasks
  external-client:
    base-url: http://localhost:8080/engine-rest
